#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: pyproject
# autospec version: v20
# autospec commit: a19cdc7
#
Name     : pypi-pycrdt
Version  : 0.10.2
Release  : 1
URL      : https://files.pythonhosted.org/packages/5f/73/5d0b070e771e46542056c6f5e4c192d1bd5ff57fa845698ea1ce95ac053f/pycrdt-0.10.2.tar.gz
Source0  : https://files.pythonhosted.org/packages/5f/73/5d0b070e771e46542056c6f5e4c192d1bd5ff57fa845698ea1ce95ac053f/pycrdt-0.10.2.tar.gz
Source1  : http://localhost/cgit/vendor/pypi-pycrdt/snapshot/pypi-pycrdt-2024-10-10-17-44-13.tar.xz
Summary  : Python bindings for Yrs
Group    : Development/Tools
License  : Apache-2.0 BSL-1.0 MIT Unicode-DFS-2016 Unlicense
Requires: pypi-pycrdt-license = %{version}-%{release}
Requires: pypi-pycrdt-python = %{version}-%{release}
Requires: pypi-pycrdt-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(maturin)
BuildRequires : pypi-maturin
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
[![Build Status](https://github.com/jupyter-server/pycrdt/actions/workflows/test.yml/badge.svg?query=branch%3Amain++)](https://github.com/jupyter-server/pycrdt/actions/workflows/test.yml/badge.svg?query=branch%3Amain++)
[![Code Coverage](https://img.shields.io/badge/coverage-100%25-green)](https://img.shields.io/badge/coverage-100%25-green)

%package license
Summary: license components for the pypi-pycrdt package.
Group: Default

%description license
license components for the pypi-pycrdt package.


%package python
Summary: python components for the pypi-pycrdt package.
Group: Default
Requires: pypi-pycrdt-python3 = %{version}-%{release}

%description python
python components for the pypi-pycrdt package.


%package python3
Summary: python3 components for the pypi-pycrdt package.
Group: Default
Requires: python3-core
Provides: pypi(pycrdt)
Requires: pypi(anyio)

%description python3
python3 components for the pypi-pycrdt package.


%prep
%setup -q -n pycrdt-0.10.2
cd %{_builddir}
tar xf %{_sourcedir}/pypi-pycrdt-2024-10-10-17-44-13.tar.xz
cd %{_builddir}/pycrdt-0.10.2
mkdir -p ./vendor
cp -r %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/* %{_builddir}/pycrdt-0.10.2/./vendor
mkdir -p .cargo
echo '[source.crates-io]
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
' >> .cargo/config.toml

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1728583517
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-pycrdt
cp %{_builddir}/pycrdt-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/pypi-pycrdt/fd298d47b3a83c50606f5b3ba1216105fbf67198 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/arc-swap/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pycrdt/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/arc-swap/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pycrdt/3c2cc74b6c4f504a5106f85ad6ff1a5b2e46b18b || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/async-lock/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pycrdt/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/async-lock/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pycrdt/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/async-trait/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pycrdt/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/async-trait/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pycrdt/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/autocfg/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pycrdt/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/autocfg/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pycrdt/e6d32072ef5f584a805b429ecbd4eec428316dde || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/bitflags/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pycrdt/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/bitflags/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pycrdt/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/bumpalo/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pycrdt/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/bumpalo/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pycrdt/0a1e89ac22450cb0311baa2613bc21b7131b321f || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/cfg-if/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pycrdt/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/cfg-if/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pycrdt/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/concurrent-queue/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pycrdt/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/concurrent-queue/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pycrdt/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/crossbeam-utils/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pycrdt/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/crossbeam-utils/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pycrdt/144111aa0f14ef5a181326683aa9ebbd9252bca6 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/dashmap/LICENSE %{buildroot}/usr/share/package-licenses/pypi-pycrdt/981659c962d4d6f47b27ebb02efb49da56cdd45e || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/event-listener-strategy/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pycrdt/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/event-listener-strategy/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pycrdt/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/event-listener/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pycrdt/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/event-listener/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pycrdt/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/fastrand/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pycrdt/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/fastrand/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pycrdt/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/getrandom/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pycrdt/e9b475b5dccf14bd66d72dd12a04db75eaad1a9e || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/getrandom/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pycrdt/c8eef3d34d69b1d62fd378fa02150a0bce62fd26 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/hashbrown/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pycrdt/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/hashbrown/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pycrdt/c9c1c33aee599ebfdfb0bc2aed9ea082d9e3173a || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/heck/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pycrdt/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/heck/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pycrdt/60c3522081bf15d7ac1d4c5a63de425ef253e87a || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/indoc/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pycrdt/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/indoc/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pycrdt/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/itoa/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pycrdt/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/itoa/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pycrdt/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/js-sys/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pycrdt/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/js-sys/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pycrdt/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/libc/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pycrdt/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/libc/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pycrdt/36d69bcb88153a640740000efe933b009420ce7e || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/lock_api/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pycrdt/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/lock_api/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pycrdt/9a2b6b4ad55ec42cf19fc686c74668d3a6303ae7 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/log/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pycrdt/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/log/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pycrdt/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/memchr/COPYING %{buildroot}/usr/share/package-licenses/pypi-pycrdt/dd445710e6e4caccc4f8a587a130eaeebe83f6f6 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/memchr/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pycrdt/4c8990add9180fc59efa5b0d8faf643c9709501e || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/memchr/UNLICENSE %{buildroot}/usr/share/package-licenses/pypi-pycrdt/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/memoffset/LICENSE %{buildroot}/usr/share/package-licenses/pypi-pycrdt/02bf11a87b9bbacedf2fcf4856af3b933faef82e || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/once_cell/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pycrdt/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/once_cell/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pycrdt/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/parking/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pycrdt/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/parking/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pycrdt/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/parking_lot_core/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pycrdt/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/parking_lot_core/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pycrdt/9a2b6b4ad55ec42cf19fc686c74668d3a6303ae7 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/pin-project-lite/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pycrdt/598f87f072f66e2269dd6919292b2934dbb20492 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/pin-project-lite/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pycrdt/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/portable-atomic/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pycrdt/598f87f072f66e2269dd6919292b2934dbb20492 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/portable-atomic/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pycrdt/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/proc-macro2/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pycrdt/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/proc-macro2/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pycrdt/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/pyo3-build-config/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pycrdt/5bb5828e544f63bd76c1b7112981a1ad86ae77f9 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/pyo3-build-config/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pycrdt/959ce149b1615b8bff3437f59282396756987859 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/pyo3-ffi/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pycrdt/5bb5828e544f63bd76c1b7112981a1ad86ae77f9 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/pyo3-ffi/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pycrdt/959ce149b1615b8bff3437f59282396756987859 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/pyo3-macros-backend/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pycrdt/5bb5828e544f63bd76c1b7112981a1ad86ae77f9 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/pyo3-macros-backend/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pycrdt/959ce149b1615b8bff3437f59282396756987859 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/pyo3-macros/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pycrdt/5bb5828e544f63bd76c1b7112981a1ad86ae77f9 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/pyo3-macros/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pycrdt/959ce149b1615b8bff3437f59282396756987859 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/pyo3/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pycrdt/5bb5828e544f63bd76c1b7112981a1ad86ae77f9 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/pyo3/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pycrdt/959ce149b1615b8bff3437f59282396756987859 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/pyo3/pyo3-runtime/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pycrdt/5bb5828e544f63bd76c1b7112981a1ad86ae77f9 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/pyo3/pyo3-runtime/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pycrdt/959ce149b1615b8bff3437f59282396756987859 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/quote/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pycrdt/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/quote/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pycrdt/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/redox_syscall/LICENSE %{buildroot}/usr/share/package-licenses/pypi-pycrdt/a00165152c82ea55b9fc254890dc8860c25e3bb6 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/ryu/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pycrdt/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/ryu/LICENSE-BOOST %{buildroot}/usr/share/package-licenses/pypi-pycrdt/3cba29011be2b9d59f6204d6fa0a386b1b2dbd90 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/scopeguard/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pycrdt/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/scopeguard/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pycrdt/f498d95a48889a0b1432e420e6754881eff1d593 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/serde/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pycrdt/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/serde/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pycrdt/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/serde_derive/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pycrdt/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/serde_derive/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pycrdt/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/serde_json/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pycrdt/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/serde_json/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pycrdt/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/smallstr/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pycrdt/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/smallstr/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pycrdt/26c7bcef21855d0111188554b58454d680b91b29 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/smallvec/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pycrdt/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/smallvec/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pycrdt/c61640f6c218caf86d1b8072e09668a8362dba04 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/syn/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pycrdt/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/syn/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pycrdt/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/target-lexicon/LICENSE %{buildroot}/usr/share/package-licenses/pypi-pycrdt/f137043e018f2024e0414a9153ea728c203ae8e5 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/thiserror-impl/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pycrdt/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/thiserror-impl/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pycrdt/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/thiserror/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pycrdt/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/thiserror/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pycrdt/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/unicode-ident/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pycrdt/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/unicode-ident/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pycrdt/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/unicode-ident/LICENSE-UNICODE %{buildroot}/usr/share/package-licenses/pypi-pycrdt/583a5eebcf6119730bd96922e8a0faecf7faf720 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/unindent/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pycrdt/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/unindent/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pycrdt/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/wasi/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pycrdt/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/wasi/LICENSE-Apache-2.0_WITH_LLVM-exception %{buildroot}/usr/share/package-licenses/pypi-pycrdt/f137043e018f2024e0414a9153ea728c203ae8e5 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/wasi/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pycrdt/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/wasm-bindgen-backend/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pycrdt/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/wasm-bindgen-backend/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pycrdt/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/wasm-bindgen-macro-support/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pycrdt/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/wasm-bindgen-macro-support/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pycrdt/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/wasm-bindgen-macro/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pycrdt/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/wasm-bindgen-macro/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pycrdt/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/wasm-bindgen-shared/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pycrdt/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/wasm-bindgen-shared/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pycrdt/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/wasm-bindgen/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pycrdt/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/wasm-bindgen/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pycrdt/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/windows-targets/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-pycrdt/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/windows-targets/license-mit %{buildroot}/usr/share/package-licenses/pypi-pycrdt/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/windows_aarch64_gnullvm/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-pycrdt/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/windows_aarch64_gnullvm/license-mit %{buildroot}/usr/share/package-licenses/pypi-pycrdt/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/windows_aarch64_msvc/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-pycrdt/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/windows_aarch64_msvc/license-mit %{buildroot}/usr/share/package-licenses/pypi-pycrdt/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/windows_i686_gnu/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-pycrdt/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/windows_i686_gnu/license-mit %{buildroot}/usr/share/package-licenses/pypi-pycrdt/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/windows_i686_gnullvm/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-pycrdt/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/windows_i686_gnullvm/license-mit %{buildroot}/usr/share/package-licenses/pypi-pycrdt/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/windows_i686_msvc/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-pycrdt/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/windows_i686_msvc/license-mit %{buildroot}/usr/share/package-licenses/pypi-pycrdt/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/windows_x86_64_gnu/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-pycrdt/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/windows_x86_64_gnu/license-mit %{buildroot}/usr/share/package-licenses/pypi-pycrdt/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/windows_x86_64_gnullvm/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-pycrdt/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/windows_x86_64_gnullvm/license-mit %{buildroot}/usr/share/package-licenses/pypi-pycrdt/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/windows_x86_64_msvc/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-pycrdt/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/pypi-pycrdt-2024-10-10-17-44-13/windows_x86_64_msvc/license-mit %{buildroot}/usr/share/package-licenses/pypi-pycrdt/689ec0681815ecc32bee639c68e7740add7bd301 || :
python3 -m installer --destdir=%{buildroot} dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-pycrdt/02bf11a87b9bbacedf2fcf4856af3b933faef82e
/usr/share/package-licenses/pypi-pycrdt/0a1e89ac22450cb0311baa2613bc21b7131b321f
/usr/share/package-licenses/pypi-pycrdt/144111aa0f14ef5a181326683aa9ebbd9252bca6
/usr/share/package-licenses/pypi-pycrdt/26c7bcef21855d0111188554b58454d680b91b29
/usr/share/package-licenses/pypi-pycrdt/36d69bcb88153a640740000efe933b009420ce7e
/usr/share/package-licenses/pypi-pycrdt/3b042d3d971924ec0296687efd50dbe08b734976
/usr/share/package-licenses/pypi-pycrdt/3c2cc74b6c4f504a5106f85ad6ff1a5b2e46b18b
/usr/share/package-licenses/pypi-pycrdt/3cba29011be2b9d59f6204d6fa0a386b1b2dbd90
/usr/share/package-licenses/pypi-pycrdt/4c8990add9180fc59efa5b0d8faf643c9709501e
/usr/share/package-licenses/pypi-pycrdt/5798832c31663cedc1618d18544d445da0295229
/usr/share/package-licenses/pypi-pycrdt/583a5eebcf6119730bd96922e8a0faecf7faf720
/usr/share/package-licenses/pypi-pycrdt/598f87f072f66e2269dd6919292b2934dbb20492
/usr/share/package-licenses/pypi-pycrdt/5bb5828e544f63bd76c1b7112981a1ad86ae77f9
/usr/share/package-licenses/pypi-pycrdt/60c3522081bf15d7ac1d4c5a63de425ef253e87a
/usr/share/package-licenses/pypi-pycrdt/689ec0681815ecc32bee639c68e7740add7bd301
/usr/share/package-licenses/pypi-pycrdt/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a
/usr/share/package-licenses/pypi-pycrdt/959ce149b1615b8bff3437f59282396756987859
/usr/share/package-licenses/pypi-pycrdt/981659c962d4d6f47b27ebb02efb49da56cdd45e
/usr/share/package-licenses/pypi-pycrdt/9a2b6b4ad55ec42cf19fc686c74668d3a6303ae7
/usr/share/package-licenses/pypi-pycrdt/9f3c36d2b7d381d9cf382a00166f3fbd06783636
/usr/share/package-licenses/pypi-pycrdt/a00165152c82ea55b9fc254890dc8860c25e3bb6
/usr/share/package-licenses/pypi-pycrdt/a3b3a65335e78bde163f84d599fa899776552994
/usr/share/package-licenses/pypi-pycrdt/c61640f6c218caf86d1b8072e09668a8362dba04
/usr/share/package-licenses/pypi-pycrdt/c8eef3d34d69b1d62fd378fa02150a0bce62fd26
/usr/share/package-licenses/pypi-pycrdt/c9c1c33aee599ebfdfb0bc2aed9ea082d9e3173a
/usr/share/package-licenses/pypi-pycrdt/ce3a2603094e799f42ce99c40941544dfcc5c4a5
/usr/share/package-licenses/pypi-pycrdt/dd445710e6e4caccc4f8a587a130eaeebe83f6f6
/usr/share/package-licenses/pypi-pycrdt/e6d32072ef5f584a805b429ecbd4eec428316dde
/usr/share/package-licenses/pypi-pycrdt/e9b475b5dccf14bd66d72dd12a04db75eaad1a9e
/usr/share/package-licenses/pypi-pycrdt/f137043e018f2024e0414a9153ea728c203ae8e5
/usr/share/package-licenses/pypi-pycrdt/f498d95a48889a0b1432e420e6754881eff1d593
/usr/share/package-licenses/pypi-pycrdt/fd298d47b3a83c50606f5b3ba1216105fbf67198
/usr/share/package-licenses/pypi-pycrdt/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
